### ISSUE TITLE
Improve poor FreeIPA scaling

### ISSUE THREAD

**Issue by ElliottKasoar** [stfc/st2-cloud-pack#43]
Creating and deleting FreeIPA users scales very poorly, which appears to be significantly affected by the output steps. For example:

With current output:
- Creating 5 users: 8s
- Creating 50 users: 252s
- Deleting 5 users: 6s
- Deleting 50 users: 101s

With no output:
- Creating 5 users: 6s
- Creating 50 users: 97s
- Deleting 5 users: 5s
- Deleting 50 users: 43s

**Comment by joelvdavies** [comment]
Just to add some info to this, Elliott tried removing the print_usernames task and performance increased quite significantly. It appears its the loops in the workflows that add a lot of the time (see https://github.com/StackStorm/st2/issues/4882).

**Comment by ElliottKasoar** [comment]
This issue is not directly tied to the output, as similar issues occur with the output removed once 100+ users are being created or deleted - the creation/deletion itself on FreeIPA is occurs relatively quickly, but the action is very slow to finish.

Calling a single script once, which loops over the users (e.g. https://github.com/stfc/ansible-jupyter/tree/main/scripts) appears to be far more efficient. Subbing these scripts in for the built-in action may be the best approach.

**Comment by DavidFair** [comment]
Closed as wont fix, as we've switched to a script
