### ISSUE TITLE
Improve hypervisor polling sensor

### ISSUE THREAD

**Issue by Ziggiyzoo** [stfc/st2-cloud-pack#68]
Improve the hypervisor polling sensor by adding in:

- Check for the Hypervisor version to ensure already up to date Hypervisors are not being updated again
- Add trigger that runs an action to reboot the list of hypervisors provided by the sensor

**Comment by anish-mudaraddi** [comment]
We need rethink and rewrite how we're doing the hypervisor polling sensor - closing this and making a new issue
